---
title: "Collaborator demographics and expertise survey"
author: "Tamas Nagy"
format: 
  html: default
  pdf: default
toc: true
toc_float: true
toc-location: left
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#| include: false

library(tidyverse)
library(googlesheets4)
library(skimr)
library(ggalluvial)

theme_set(theme_light())

```


```{r read_data, include=FALSE}
# Read data

current_year <- 2024
qrp_collab_form_id <- "1S9uab6LLN9BrDVKzYHBvbftRhIdNv9C5mlc-O-qCfEk"

qrp_form_raw <- range_read(qrp_collab_form_id)

# Process data: create variable names, calculate number of years

qrp_form <- 
  qrp_form_raw |> 
  # One participant misread the question and answered in number of years instead of years. Fixing that here.
  mutate(across(c(`Which year have you started conducting quantitative empirical research?`,
                  `Which year have you started conducting meta-scientific research?`),
                ~if_else(. < 1000, 2024-., .) )) |> 
  transmute(id = row_number(),
            age = current_year - `Please state your year of birth.`,
            gender = `Please state your gender.`,
            ethnicity = `Please state your race/ ethnicity.`,
            neurotype = `Which of these neurotypes apply to you?`,
            start_position = `What best describes your academic position AT THE START OF THE PROJECT (June 2022)?`,
            current_position = `What best describes your CURRENT academic position?`,
            training_field = `What field are you trained in (what was the degree you obtained or are currently obtaining)?`,
            research_fields = `In which psychological subdisciplines do you conduct research?`,
            research_methods = `Which types of research methods have you used or are you currently using?`,
            research_age = current_year - `Which year have you started conducting quantitative empirical research?`,
            metaresearch_age = current_year - `Which year have you started conducting meta-scientific research?`,
            publications = `How many peer-reviewed publications have you co-authored (including the ones where you are first author)?`,
            publication_age = current_year - `Which year did you publish your first quantitative empirical peer-reviewed article (as a first author or co-author)?`,
            h_index = `corrected h-index`,
            no_sips = `How many SIPS have you attended AT THE START OF THE PROJECT (June 2022; including the SIPS in Victoria, BC)?`
          ) |> 
  # Aggregate ethnicity responses
  mutate(ethnicity = if_else(str_detect(ethnicity, "White|white|European|Caucasian"), "Caucasian", ethnicity),
         current_position = if_else(str_detect(current_position, "Research"), "Research professional/scientist", current_position)) |> 
  # Remove duplicate cases
  group_by(age, gender, ethnicity, start_position, current_position, training_field, research_fields) |> 
  slice(1) |>
  ungroup()

  

```

## Age, gender, race/ethnicity, neurotype of collaborators
```{r demographics}
qrp_form |> 
  select(age, gender, ethnicity, neurotype) |> 
  skim()

qrp_form |> 
  ggplot() +
  aes(y = gender) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Gender", y = NULL)

qrp_form |> 
  ggplot() +
  aes(y = ethnicity) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Ethnicity", y = NULL)

qrp_form |> 
  # select(id, neurotype) |> 
  # separate_rows(neurotype, sep = ", ") |> 
  ggplot() +
  aes(y = neurotype) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Neurotype", y = NULL)
  

```


## Position in 2022 and now
```{r position}
qrp_form |> 
  ggplot() +
  aes(y = start_position) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Starting position (2022)", y = NULL)

qrp_form |> 
  ggplot() +
  aes(y = current_position) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Current position (2024)", y = NULL)


qrp_form |> 
  select(id, start_position, current_position) |> 
  ggplot() +
  aes(axis1 = start_position, axis2 = current_position, label = after_stat(stratum), fill = after_stat(stratum)) +
  geom_flow(aes(fill = start_position), show.legend = FALSE) +
  geom_stratum(show.legend = FALSE) +
  geom_text(stat = "stratum") +
  labs(title = "Changes in positions from start to end of project") +
  theme_void()

```

## Field of training and research. Research age, meta-research age, SIPS attended
```{r training_research_age}
qrp_form |> 
  ggplot() +
  aes(y = training_field) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Field of training", y = NULL)

qrp_form |> 
  ggplot() +
  aes(y = no_sips) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(title = "Number of SIPS attended until 2022", y = NULL)

qrp_form |> 
  select(research_age, metaresearch_age) |> 
  skim()
  
```

## Research output: no. of publications, publication age, h-index, 
```{r research_output}
qrp_form |> 
  select(publication_age, publications, h_index) |> 
  skim()


```

## Field of interest, methods used

```{r expertise}

fields_long <- 
  qrp_form |> 
  select(id, research_fields) |> 
  separate_rows(research_fields, sep = ", ")

fields_long |> 
  ggplot() +
  aes(y = fct_rev(fct_infreq(research_fields))) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(y = NULL, title = "Number of collaborators with expertise in a specific field")


methods_long <- 
  qrp_form |> 
  select(id, research_methods) |> 
  separate_rows(research_methods, sep = ", ")

methods_long |> 
  ggplot() +
  aes(y = fct_rev(fct_infreq(research_methods))) +
  geom_bar() +
  scale_x_continuous(breaks = scales::pretty_breaks()) + 
  labs(y = NULL, title = "Number of collaborators with expertise in a specific method")


```



